# Generated by Django 3.1.6 on 2021-02-13 09:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import froala_editor.fields
import tour.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام\u200cشهر')),
                ('name_en', models.CharField(default='', max_length=50, verbose_name='نام\u200cشهر-انگلیسی')),
                ('image', models.ImageField(upload_to='cities', verbose_name='تصویر')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('continent', models.CharField(max_length=50, verbose_name='قاره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('geographic_place', models.CharField(max_length=100, verbose_name='موقعیت جغرافیایی')),
                ('currency', models.CharField(max_length=30, verbose_name='ارز رایج')),
                ('language', models.CharField(max_length=30, verbose_name='زبان')),
                ('religion', models.CharField(max_length=30, verbose_name='دین')),
                ('description_content', froala_editor.fields.FroalaField(verbose_name='توضیحات کامل')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('title_en', models.CharField(default='', max_length=50, verbose_name='عنوان-انگلیسی')),
                ('image', models.ImageField(upload_to=tour.models.ImagePath, verbose_name='تصویر')),
                ('label', models.CharField(max_length=20, verbose_name='برچسب')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('wearings', models.CharField(max_length=250, null=True, verbose_name='پوشیدنی ها')),
                ('tour_duration', models.CharField(max_length=100, verbose_name='مدت زمان تور')),
                ('included_costs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None, verbose_name='هزینه های مشمول')),
                ('not_included_costs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None, verbose_name='هزینه های مستثنی')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None, verbose_name='امکانات')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('adult_price', models.IntegerField(verbose_name='قیمت مسافران بالغ')),
                ('child_price', models.IntegerField(default=0, verbose_name='قیمت مسافران کودک')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع تور')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ اتمام تور')),
                ('passengers', models.IntegerField(verbose_name='تعداد مسافران')),
                ('passengers_left', models.IntegerField(default=models.IntegerField(verbose_name='تعداد مسافران'), verbose_name='مسافران باقیمانده')),
                ('tour_type', models.CharField(max_length=30, verbose_name='نوع تور')),
                ('off_percent', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=0, verbose_name='تور فعال است')),
                ('date_created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.citymodel', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'تور گردشگری',
                'verbose_name_plural': 'تور های گردشگری',
                'ordering': ['-start_date'],
            },
        ),
    ]
