# Generated by Django 3.1.6 on 2021-02-15 05:44

from django.db import migrations, models
import tour.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='cities', verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=tour.models.ImagePath, verbose_name='تصویر بندانگشتی'),
        ),
    ]
