# Generated by Django 3.1.6 on 2021-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210215_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
