# Generated by Django 3.1.6 on 2021-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20210217_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tourmodel',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
